(local yoda (require :yoda-fnl))
(local cloud (yoda.read trajectory {:type 2}))
(assert (> cloud.nop 0))
(local types (yoda.chill-plus cloud {:cutoff 3.5 :type 2}))
(print (string.format "idiomatic_fnl nop=%d ntypes=%d" cloud.nop (length types)))
